import { Game, Notification, UserProfile } from './types'

// Generate price history data
const generatePriceHistory = (basePrice: number, months: number = 12) => {
  const history = []
  const now = new Date()
  
  for (let i = months; i >= 0; i--) {
    const date = new Date(now)
    date.setMonth(date.getMonth() - i)
    const variance = (Math.random() - 0.5) * basePrice * 0.6
    const price = Math.max(basePrice * 0.3, Math.min(basePrice * 1.1, basePrice + variance))
    history.push({
      date: date.toISOString().split('T')[0],
      price: Math.round(price * 100) / 100
    })
  }
  
  return history
}

export const mockUser: UserProfile = {
  id: 'user-1',
  name: 'Carlos Rodriguez',
  email: 'carlos.rodriguez@email.com',
  gamertag: 'xCarlosGamer',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
  plan: 'free',
  memberSince: '2024-01-15',
  alertsEnabled: true,
  priceDropAlerts: true,
  lowestEverAlerts: true,
  wishlistAlerts: true
}

export const mockGames: Game[] = [
  {
    id: '1',
    title: 'Starfield',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1716740/library_600x900_2x.jpg',
    currentPrice: 34.99,
    originalPrice: 69.99,
    lowestPrice: 29.99,
    highestPrice: 69.99,
    discount: 50,
    isFavorite: true,
    priceHistory: generatePriceHistory(69.99),
    platform: 'Xbox Series X|S',
    releaseDate: '2023-09-06',
    rating: 4.2,
    category: 'RPG',
    xboxStoreUrl: 'https://www.xbox.com/games/store/starfield/9ncls0dls04h'
  },
  {
    id: '2',
    title: 'Forza Horizon 5',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1551360/library_600x900_2x.jpg',
    currentPrice: 29.99,
    originalPrice: 59.99,
    lowestPrice: 24.99,
    highestPrice: 59.99,
    discount: 50,
    isFavorite: true,
    priceHistory: generatePriceHistory(59.99),
    platform: 'All',
    releaseDate: '2021-11-09',
    rating: 4.8,
    category: 'Racing',
    xboxStoreUrl: 'https://www.xbox.com/games/store/forza-horizon-5/9nxn39crlgml'
  },
  {
    id: '3',
    title: 'Halo Infinite',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1240440/library_600x900_2x.jpg',
    currentPrice: 19.99,
    originalPrice: 59.99,
    lowestPrice: 14.99,
    highestPrice: 59.99,
    discount: 67,
    isFavorite: false,
    priceHistory: generatePriceHistory(59.99),
    platform: 'All',
    releaseDate: '2021-12-08',
    rating: 4.5,
    category: 'Shooter',
    xboxStoreUrl: 'https://www.xbox.com/games/store/halo-infinite/9pp5g1f0c2b6'
  },
  {
    id: '4',
    title: 'Sea of Thieves',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1172620/library_600x900_2x.jpg',
    currentPrice: 19.99,
    originalPrice: 39.99,
    lowestPrice: 9.99,
    highestPrice: 39.99,
    discount: 50,
    isFavorite: false,
    priceHistory: generatePriceHistory(39.99),
    platform: 'All',
    releaseDate: '2018-03-20',
    rating: 4.3,
    category: 'Adventure',
    xboxStoreUrl: 'https://www.xbox.com/games/store/sea-of-thieves/9p2n57mc619k'
  },
  {
    id: '5',
    title: 'Microsoft Flight Simulator',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1250410/library_600x900_2x.jpg',
    currentPrice: 44.99,
    originalPrice: 59.99,
    lowestPrice: 29.99,
    highestPrice: 59.99,
    discount: 25,
    isFavorite: false,
    priceHistory: generatePriceHistory(59.99),
    platform: 'All',
    releaseDate: '2020-08-18',
    rating: 4.7,
    category: 'Simulation',
    xboxStoreUrl: 'https://www.xbox.com/games/store/microsoft-flight-simulator-standard/9nxn8gf8n9ht'
  },
  {
    id: '6',
    title: 'Gears 5',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1097840/library_600x900_2x.jpg',
    currentPrice: 9.99,
    originalPrice: 39.99,
    lowestPrice: 9.99,
    highestPrice: 39.99,
    discount: 75,
    isFavorite: false,
    priceHistory: generatePriceHistory(39.99),
    platform: 'All',
    releaseDate: '2019-09-10',
    rating: 4.6,
    category: 'Shooter',
    xboxStoreUrl: 'https://www.xbox.com/games/store/gears-5/c2kdnlt2h7dm'
  },
  {
    id: '7',
    title: 'Age of Empires IV',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1466860/library_600x900_2x.jpg',
    currentPrice: 29.99,
    originalPrice: 59.99,
    lowestPrice: 19.99,
    highestPrice: 59.99,
    discount: 50,
    isFavorite: false,
    priceHistory: generatePriceHistory(59.99),
    platform: 'PC',
    releaseDate: '2021-10-28',
    rating: 4.4,
    category: 'Strategy',
    xboxStoreUrl: 'https://www.xbox.com/games/store/age-of-empires-iv/9p4924nq30c7'
  },
  {
    id: '8',
    title: 'Diablo IV',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2344520/library_600x900_2x.jpg',
    currentPrice: 49.99,
    originalPrice: 69.99,
    lowestPrice: 39.99,
    highestPrice: 69.99,
    discount: 29,
    isFavorite: true,
    priceHistory: generatePriceHistory(69.99),
    platform: 'All',
    releaseDate: '2023-06-06',
    rating: 4.3,
    category: 'RPG',
    xboxStoreUrl: 'https://www.xbox.com/games/store/diablo-iv/9p3v5827kq4m'
  },
  {
    id: '9',
    title: 'Call of Duty: MW III',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2519060/library_600x900_2x.jpg',
    currentPrice: 39.99,
    originalPrice: 69.99,
    lowestPrice: 34.99,
    highestPrice: 69.99,
    discount: 43,
    isFavorite: false,
    priceHistory: generatePriceHistory(69.99),
    platform: 'All',
    releaseDate: '2023-11-10',
    rating: 4.1,
    category: 'Shooter',
    xboxStoreUrl: 'https://www.xbox.com/games/store/call-of-duty-modern-warfare-iii/9p4g4qfzg4zn'
  },
  {
    id: '10',
    title: 'Ori and the Will of the Wisps',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1057090/library_600x900_2x.jpg',
    currentPrice: 14.99,
    originalPrice: 29.99,
    lowestPrice: 9.99,
    highestPrice: 29.99,
    discount: 50,
    isFavorite: true,
    priceHistory: generatePriceHistory(29.99),
    platform: 'All',
    releaseDate: '2020-03-11',
    rating: 4.9,
    category: 'Adventure',
    xboxStoreUrl: 'https://www.xbox.com/games/store/ori-and-the-will-of-the-wisps/9n8cd0xzklp4'
  },
  {
    id: '11',
    title: 'Elden Ring',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/library_600x900_2x.jpg',
    currentPrice: 41.99,
    originalPrice: 59.99,
    lowestPrice: 35.99,
    highestPrice: 59.99,
    discount: 30,
    isFavorite: true,
    priceHistory: generatePriceHistory(59.99),
    platform: 'All',
    releaseDate: '2022-02-25',
    rating: 4.9,
    category: 'RPG',
    xboxStoreUrl: 'https://www.xbox.com/games/store/elden-ring/9p3j32ctxlrz'
  },
  {
    id: '12',
    title: 'Cyberpunk 2077',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1091500/library_600x900_2x.jpg',
    currentPrice: 29.99,
    originalPrice: 59.99,
    lowestPrice: 24.99,
    highestPrice: 59.99,
    discount: 50,
    isFavorite: false,
    priceHistory: generatePriceHistory(59.99),
    platform: 'All',
    releaseDate: '2020-12-10',
    rating: 4.5,
    category: 'RPG',
    xboxStoreUrl: 'https://www.xbox.com/games/store/cyberpunk-2077/bx3m8l83bbrw'
  },
  {
    id: '13',
    title: 'Red Dead Redemption 2',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1174180/library_600x900_2x.jpg',
    currentPrice: 23.99,
    originalPrice: 59.99,
    lowestPrice: 19.79,
    highestPrice: 59.99,
    discount: 60,
    isFavorite: false,
    priceHistory: generatePriceHistory(59.99),
    platform: 'All',
    releaseDate: '2019-11-05',
    rating: 4.8,
    category: 'Adventure',
    xboxStoreUrl: 'https://www.xbox.com/games/store/red-dead-redemption-2/9n2zkng3f4wq'
  },
  {
    id: '14',
    title: 'Hogwarts Legacy',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/990080/library_600x900_2x.jpg',
    currentPrice: 35.99,
    originalPrice: 59.99,
    lowestPrice: 29.99,
    highestPrice: 59.99,
    discount: 40,
    isFavorite: false,
    priceHistory: generatePriceHistory(59.99),
    platform: 'All',
    releaseDate: '2023-02-10',
    rating: 4.6,
    category: 'RPG',
    xboxStoreUrl: 'https://www.xbox.com/games/store/hogwarts-legacy/9nkh1k0z0kbq'
  },
  {
    id: '15',
    title: 'EA Sports FC 24',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2195250/library_600x900_2x.jpg',
    currentPrice: 34.99,
    originalPrice: 69.99,
    lowestPrice: 29.99,
    highestPrice: 69.99,
    discount: 50,
    isFavorite: false,
    priceHistory: generatePriceHistory(69.99),
    platform: 'All',
    releaseDate: '2023-09-29',
    rating: 4.0,
    category: 'Sports',
    xboxStoreUrl: 'https://www.xbox.com/games/store/ea-sports-fc-24/9nvlswdl66bf'
  },
  {
    id: '16',
    title: 'Minecraft',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1672970/library_600x900_2x.jpg',
    currentPrice: 19.99,
    originalPrice: 29.99,
    lowestPrice: 14.99,
    highestPrice: 29.99,
    discount: 33,
    isFavorite: true,
    priceHistory: generatePriceHistory(29.99),
    platform: 'All',
    releaseDate: '2011-11-18',
    rating: 4.8,
    category: 'Adventure',
    xboxStoreUrl: 'https://www.xbox.com/games/store/minecraft/9mvxmvt8zkwc'
  },
  {
    id: '17',
    title: "Mafia: Definitive Edition",
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1030840/library_600x900_2x.jpg',
    currentPrice: 19.99,
    originalPrice: 39.99,
    lowestPrice: 14.99,
    highestPrice: 39.99,
    discount: 50,
    isFavorite: false,
    priceHistory: generatePriceHistory(39.99),
    platform: 'All',
    releaseDate: '2020-09-25',
    rating: 4.5,
    category: 'Adventure',
    xboxStoreUrl: 'https://www.xbox.com/games/store/mafia-definitive-edition/9n19g7vs8jw6'
  },
  {
    id: '18',
    title: 'Forza Motorsport',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2440510/library_600x900_2x.jpg',
    currentPrice: 44.99,
    originalPrice: 69.99,
    lowestPrice: 39.99,
    highestPrice: 69.99,
    discount: 36,
    isFavorite: false,
    priceHistory: generatePriceHistory(69.99),
    platform: 'All',
    releaseDate: '2023-10-10',
    rating: 4.3,
    category: 'Racing',
    xboxStoreUrl: 'https://www.xbox.com/games/store/forza-motorsport/9p6dqw8xspff'
  },
  {
    id: '19',
    title: 'The Elder Scrolls V: Skyrim',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/489830/library_600x900_2x.jpg',
    currentPrice: 15.99,
    originalPrice: 39.99,
    lowestPrice: 9.99,
    highestPrice: 39.99,
    discount: 60,
    isFavorite: false,
    priceHistory: generatePriceHistory(39.99),
    platform: 'All',
    releaseDate: '2016-10-28',
    rating: 4.7,
    category: 'RPG',
    xboxStoreUrl: 'https://www.xbox.com/games/store/the-elder-scrolls-v-skyrim-special-edition/bq1w1t1fc14w'
  },
  {
    id: '20',
    title: 'Resident Evil 4',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2050650/library_600x900_2x.jpg',
    currentPrice: 29.99,
    originalPrice: 59.99,
    lowestPrice: 29.99,
    highestPrice: 59.99,
    discount: 50,
    isFavorite: false,
    priceHistory: generatePriceHistory(59.99),
    platform: 'All',
    releaseDate: '2023-03-24',
    rating: 4.8,
    category: 'Horror',
    xboxStoreUrl: 'https://www.xbox.com/games/store/resident-evil-4/9p7vgfvhlqwl'
  },
  {
    id: '21',
    title: 'Grand Theft Auto V',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/271590/library_600x900_2x.jpg',
    currentPrice: 14.99,
    originalPrice: 29.99,
    lowestPrice: 9.99,
    highestPrice: 29.99,
    discount: 50,
    isFavorite: false,
    priceHistory: generatePriceHistory(29.99),
    platform: 'All',
    releaseDate: '2015-04-14',
    rating: 4.6,
    category: 'Adventure',
    xboxStoreUrl: 'https://www.xbox.com/games/store/grand-theft-auto-v/bpj686w6s0nh'
  },
  {
    id: '22',
    title: 'Mortal Kombat 1',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1971870/library_600x900_2x.jpg',
    currentPrice: 34.99,
    originalPrice: 69.99,
    lowestPrice: 29.99,
    highestPrice: 69.99,
    discount: 50,
    isFavorite: false,
    priceHistory: generatePriceHistory(69.99),
    platform: 'All',
    releaseDate: '2023-09-19',
    rating: 4.4,
    category: 'Fighting',
    xboxStoreUrl: 'https://www.xbox.com/games/store/mortal-kombat-1/9phr5s75bwvj'
  },
  {
    id: '23',
    title: 'Palworld',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1623730/library_600x900_2x.jpg',
    currentPrice: 26.99,
    originalPrice: 29.99,
    lowestPrice: 22.49,
    highestPrice: 29.99,
    discount: 10,
    isFavorite: true,
    priceHistory: generatePriceHistory(29.99),
    platform: 'All',
    releaseDate: '2024-01-19',
    rating: 4.5,
    category: 'Adventure',
    xboxStoreUrl: 'https://www.xbox.com/games/store/palworld/9p5l3c1898vn'
  },
  {
    id: '24',
    title: 'Lies of P',
    coverImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1627720/library_600x900_2x.jpg',
    currentPrice: 35.99,
    originalPrice: 59.99,
    lowestPrice: 35.99,
    highestPrice: 59.99,
    discount: 40,
    isFavorite: false,
    priceHistory: generatePriceHistory(59.99),
    platform: 'All',
    releaseDate: '2023-09-19',
    rating: 4.6,
    category: 'RPG',
    xboxStoreUrl: 'https://www.xbox.com/games/store/lies-of-p/9n8p9c6wqgwk'
  }
]

export const mockNotifications: Notification[] = [
  {
    id: '1',
    gameId: '1',
    gameTitle: 'Starfield',
    gameCover: 'https://cdn.akamai.steamstatic.com/steam/apps/1716740/library_600x900_2x.jpg',
    type: 'price_drop',
    message: 'El precio ha bajado un 50%',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    read: false,
    newPrice: 34.99,
    oldPrice: 69.99
  },
  {
    id: '2',
    gameId: '3',
    gameTitle: 'Halo Infinite',
    gameCover: 'https://cdn.akamai.steamstatic.com/steam/apps/1240440/library_600x900_2x.jpg',
    type: 'lowest_ever',
    message: 'Precio mas bajo de la historia',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    read: false,
    newPrice: 19.99,
    oldPrice: 59.99
  },
  {
    id: '3',
    gameId: '6',
    gameTitle: 'Gears 5',
    gameCover: 'https://cdn.akamai.steamstatic.com/steam/apps/1097840/library_600x900_2x.jpg',
    type: 'wishlist_sale',
    message: 'Un juego de tu lista esta en oferta',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    read: true,
    newPrice: 9.99,
    oldPrice: 39.99
  },
  {
    id: '4',
    gameId: '2',
    gameTitle: 'Forza Horizon 5',
    gameCover: 'https://cdn.akamai.steamstatic.com/steam/apps/1551360/library_600x900_2x.jpg',
    type: 'price_drop',
    message: 'El precio ha bajado',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    read: true,
    newPrice: 29.99,
    oldPrice: 44.99
  },
  {
    id: '5',
    gameId: '11',
    gameTitle: 'Elden Ring',
    gameCover: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/library_600x900_2x.jpg',
    type: 'price_drop',
    message: 'El precio ha bajado un 30%',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    read: true,
    newPrice: 41.99,
    oldPrice: 59.99
  },
  {
    id: '6',
    gameId: '13',
    gameTitle: 'Red Dead Redemption 2',
    gameCover: 'https://cdn.akamai.steamstatic.com/steam/apps/1174180/library_600x900_2x.jpg',
    type: 'lowest_ever',
    message: 'Precio historico alcanzado',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    read: true,
    newPrice: 23.99,
    oldPrice: 59.99
  }
]
